### ISSUE TITLE
Shifting between expected hints and words in buffer

### ISSUE THREAD

**Issue by cambp4** [phaazon/hop.nvim#1]
NVIM v0.5.0-dev+1028-g702208daa
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

Hopefully you can see the issue on the picture, when we call the :VroomWord method, the results are shifted and the shortcuts don't appear on the correct words.

![vroom](https://user-images.githubusercontent.com/62029155/107160331-710b6280-694a-11eb-9df3-b61e43283546.png)

**Comment by phaazon** [comment]
Does that happen after the hints have appeared? There’s currently an issue with LSP (I see you have signs enabled), so it might be why. What happens if you close (escape) and re-open?

**Comment by cambp4** [comment]
no it does that straight after the command :VroomWord is used. I tried to escape and then restart the command it does the same. yes I am using LSP (Coc) with clangd. I also tried to restart nvim but it does fix the issue.

**Comment by phaazon** [comment]
Are you using tab?

**Comment by cambp4** [comment]
that's my settings

set backspace=indent,eol,start
set autoindent
set smartindent
set shiftwidth=4
set shiftround
set softtabstop=4
set tabstop=4
set smarttab
set expandtab
set lazyredraw
set formatoptions+=j

**Comment by phaazon** [comment]
Thanks, I’ll try to reproduce it and fix it. Does it behave like that for markdown files or any file without an LSP?

**Comment by cambp4** [comment]
I just tried with my cpp files so far, I'll try to do more testing in the following days :)

**Comment by phaazon** [comment]
I have fixed a bunch of things relating to the topic today, any news on your side? Right now, two remaining things that might get in the way about this weird offset bug:

- Some multi-bytes characters on not well supported (i.e. emojis).
- Currently, `nowrap` mode works only. `wrap` is completely broken and I’ll work on that soon. The fix is not hard and I already know how to fix it but it’ll come a bit later.

I’m interested to see whether you still have your initial problem.

**Comment by cambp4** [comment]
hi, after the update the issue is still present as you can see on this screenshot. it does it as well with file that does not have lsp.

![hop](https://user-images.githubusercontent.com/62029155/107710378-ad58fe80-6c7b-11eb-830e-12893f9a6ca5.png)

**Comment by cambp4** [comment]
also there is something related but slightly different, after having reformated my buffer using clang format, when I relaunched :HopWord everything was shifted. I had to do a :bd on the buffer and reopen it to go back to a normal behaviour.

![hop2](https://user-images.githubusercontent.com/62029155/107712067-99160100-6c7d-11eb-864f-ce109520e0ad.png)

**Comment by phaazon** [comment]
You were still probably in the hop buffer. I don’t reproduce your issue so maybe it’s linked to something related to your config I haven’t tested yet. I’ll give it a test tomorrow. :)

**Comment by cambp4** [comment]
ok, so I just noticed that the shifting between hints and the location of the words might be due to tabs : 

I'm working with cpp files and I use lsp to auto format my files using clangd, it's something really common to have tools that autoformat files so I think it could be a bug that impact a lot of people.

this is a screenshot of hints when on a file that has been auto formated 
![image](https://user-images.githubusercontent.com/62029155/108639141-d99a2980-748a-11eb-9961-55ee274be276.png)
 
and once I replace tabs by spaces
 
![image](https://user-images.githubusercontent.com/62029155/108639173-19f9a780-748b-11eb-8cfd-cc3352ff05ac.png)

also sorry if this information is in the documentation but I just wanted to mention as well that I am colour blind (like actually quite a lot of people) and I really struggle to see the hints, is possible to customize the colour of the hints?
easymotion default colour works well for instance

![image](https://user-images.githubusercontent.com/62029155/108639256-81aff280-748b-11eb-8a84-9179cced11d0.png)

**Comment by cambp4** [comment]
ok so quick update, the command :retab replace all tabs by spaces automatically and seems to fix the glitch, it might be worth mentioning this on the readme page. so that people can call this before HopWord

**Comment by phaazon** [comment]
Hello,

Spent a bit of time on this lately and two important points:

1. I don’t want to modify the existing buffer. This is by-contract rule of Hop: it doesn’t modify the existing buffer.
2. Things like `tabstop` cannot be used because, for whatever obscure reasons, there doesn’t seem to be a direct mapping between tabs and space counts. As an exemple, I was able to insert two tabs in a document that are represented with a different amount of spaces. The joined picture shows that the first tab is two-space wide and the second tab is one-space wide.

![img_022521_201242](https://user-images.githubusercontent.com/506592/109204593-d4e4b680-77a5-11eb-9898-b9e78ba2b502.png)

I think a proper way to fix this is to actually fix all the issues with alignments at once by switching to extmarks. I’ll try to investigate that in the upcoming days. If people want a mitigation by modifying the content of their buffer before calling Hop, that’s fine but this is not Hop will (ever) do.

**Comment by cambp4** [comment]
thanks for the update, I agree modifying the buffer is really not a good idea. a hack I was thinking of was to do retab and once hop is done do a undo but god this is ugly.

**Comment by phaazon** [comment]
I _think_ extmarks should fix that. They will be the next thing I do with Hop. :)

**Comment by phaazon** [comment]
@cambp4 can I have an update on your issue? Is this fixed for you? :)

**Comment by phaazon** [comment]
I’m closing the issue as I think it is resolved, but please feel free to reach out if you think it should be re-opened.
